"""
Builtin Preset-Definitionen für TmYNoobs VoiceMorph.

Jedes Preset ist ein dict mit:
  name        – Anzeigename
  description – Kurzbeschreibung für Tooltip
  icon        – Emoji-Icon für die UI
  params      – Effekt-Parameter
"""

BUILTIN_PRESETS = [
    {
        "id": "bypass",
        "name": "Kein Effekt",
        "description": "Stimme ohne Veränderung – so wie du wirklich klingst.",
        "icon": "🎤",
        "params": {
            "pitch_semitones": 0.0,
            "reverb_room_size": 0.0,
            "reverb_wet_level": 0.0,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 0.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "robot",
        "name": "Roboter",
        "description": "Klingt wie ein futuristischer Roboter – Ringmodulation + Bitcrush.",
        "icon": "🤖",
        "params": {
            "pitch_semitones": 0.0,
            "reverb_room_size": 0.3,
            "reverb_wet_level": 0.2,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 10.0,
            "lowpass_hz": 18000.0,
            "highpass_hz": 200.0,
            "ringmod_hz": 80.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 6,
        },
    },
    {
        "id": "chipmunk",
        "name": "Chipmunk",
        "description": "Super hoch und piepsig – perfekt zum Nerven von Freunden.",
        "icon": "🐿️",
        "params": {
            "pitch_semitones": 8.0,
            "reverb_room_size": 0.1,
            "reverb_wet_level": 0.1,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 0.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "deep_voice",
        "name": "Deep Voice",
        "description": "Tief, dunkel und beeindruckend – wie ein Filmerzähler.",
        "icon": "🎙️",
        "params": {
            "pitch_semitones": -6.0,
            "reverb_room_size": 0.5,
            "reverb_wet_level": 0.3,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 0.0,
            "lowpass_hz": 8000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "telephone",
        "name": "Telefon",
        "description": "Klingt wie ein alter Telefonanruf – eng und charakteristisch.",
        "icon": "📞",
        "params": {
            "pitch_semitones": 0.0,
            "reverb_room_size": 0.0,
            "reverb_wet_level": 0.0,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 8.0,
            "lowpass_hz": 3400.0,
            "highpass_hz": 300.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "echo_hall",
        "name": "Echo & Hall",
        "description": "Klingt wie in einer riesigen Kathedrale – viel Hall und Echo.",
        "icon": "🏛️",
        "params": {
            "pitch_semitones": 0.0,
            "reverb_room_size": 0.95,
            "reverb_wet_level": 0.7,
            "delay_seconds": 0.35,
            "delay_feedback": 0.4,
            "distortion_drive": 0.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "alien",
        "name": "Alien",
        "description": "Unirdisch fremd – Ringmodulation, Pitch-Shift und Tremolo.",
        "icon": "👽",
        "params": {
            "pitch_semitones": 4.0,
            "reverb_room_size": 0.3,
            "reverb_wet_level": 0.25,
            "delay_seconds": 0.1,
            "delay_feedback": 0.3,
            "distortion_drive": 5.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 150.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 6.0,
            "tremolo_depth": 0.6,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "helium",
        "name": "Helium 😂",
        "description": "So hoch wie möglich – als hättest du einen Luftballon geatmet!",
        "icon": "🎈",
        "params": {
            "pitch_semitones": 12.0,
            "reverb_room_size": 0.1,
            "reverb_wet_level": 0.0,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 0.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "movie_villain",
        "name": "Movie Villain",
        "description": "Du bist jetzt der Bösewicht – tief, bedrohlich, dramatisch.",
        "icon": "😈",
        "params": {
            "pitch_semitones": -8.0,
            "reverb_room_size": 0.7,
            "reverb_wet_level": 0.5,
            "delay_seconds": 0.0,
            "delay_feedback": 0.0,
            "distortion_drive": 15.0,
            "lowpass_hz": 5000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.0,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
    {
        "id": "stadium",
        "name": "Stadion",
        "description": "Wie eine Ansage im Fußballstadion – riesig und hallend.",
        "icon": "🏟️",
        "params": {
            "pitch_semitones": 0.0,
            "reverb_room_size": 1.0,
            "reverb_wet_level": 0.8,
            "delay_seconds": 0.2,
            "delay_feedback": 0.5,
            "distortion_drive": 0.0,
            "lowpass_hz": 20000.0,
            "highpass_hz": 20.0,
            "ringmod_hz": 0.0,
            "chorus_depth": 0.5,
            "tremolo_rate": 0.0,
            "tremolo_depth": 0.0,
            "bitcrush_bits": 0,
        },
    },
]

# Alle Standard-Parameter für leere Custom-Presets
DEFAULT_PARAMS = {
    "pitch_semitones": 0.0,
    "reverb_room_size": 0.0,
    "reverb_wet_level": 0.0,
    "delay_seconds": 0.0,
    "delay_feedback": 0.0,
    "distortion_drive": 0.0,
    "lowpass_hz": 20000.0,
    "highpass_hz": 20.0,
    "ringmod_hz": 0.0,
    "chorus_depth": 0.0,
    "tremolo_rate": 0.0,
    "tremolo_depth": 0.0,
    "bitcrush_bits": 0,
}

PARAM_DESCRIPTIONS = {
    "pitch_semitones":  ("Pitch (Tonhöhe)",      "Halbtöne",  -12.0, 12.0,  0.0),
    "reverb_room_size": ("Raumgröße (Hall)",      "",           0.0,  1.0,   0.0),
    "reverb_wet_level": ("Hall-Intensität",       "",           0.0,  1.0,   0.0),
    "delay_seconds":    ("Echo-Verzögerung",      "Sekunden",   0.0,  1.0,   0.0),
    "delay_feedback":   ("Echo-Wiederholung",     "",           0.0,  0.95,  0.0),
    "distortion_drive": ("Verzerrung",            "",           0.0,  30.0,  0.0),
    "lowpass_hz":       ("Hochtonfilter (Lowpass)","Hz",        500.0,20000.0,20000.0),
    "highpass_hz":      ("Tieftonfilter (Highpass)","Hz",       20.0, 5000.0, 20.0),
    "ringmod_hz":       ("Ringmod-Frequenz",      "Hz",         0.0,  500.0,  0.0),
    "chorus_depth":     ("Chorus-Tiefe",          "",           0.0,  1.0,   0.0),
    "tremolo_rate":     ("Tremolo-Geschwindigkeit","Hz",        0.0,  15.0,  0.0),
    "tremolo_depth":    ("Tremolo-Stärke",        "",           0.0,  1.0,   0.0),
    "bitcrush_bits":    ("Bitcrush (Lo-Fi)",      "Bit",        0,    16,    0),
}
